sudo: true
language: c
before_install:
  - sudo apt-get install libev-dev build-essential cpanminus
  - wget http://nginx.org/download/nginx-1.9.15.tar.gz
  - tar -zxf nginx-1.9.15.tar.gz
script:
  - (cd nginx-1.9.15 && ./configure --add-module=/home/travis/build/x-v8/ngx_http_auth_file_module && make -j4 && sudo make install)
  - sudo cpanm Test::Nginx
  - make test
